/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the featureList.xml at
   Wed Aug 12 2015 14:10:40 GMT-0700 (PDT)
   Please do not edit this file.
 */

var parseFeatureReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseFeatureRequire')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
featureList = module.exports;

featureList.registerFeature = function() {
  parseFeatureReq.rbac.addFeatureAccess('smConfigure', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('smMonitoring', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('baremetal', 'all', 'all');
}

