/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */
// File generated by Makefile target ui-schemas
define([], function(){ return {
    "properties": {
        "id": {
            "viewable": true,
            "editable": false,
            "label": "ID",
            "path": "properties.id"
        },
        "email": {
            "viewable": true,
            "editable": true,
            "label": "Email",
            "path": "properties.email"
        },
        "base_image_id": {
            "viewable": true,
            "editable": true,
            "label": "Configured OS Image",
            "path": "properties.base_image_id"
        },
        "package_image_id": {
            "viewable": true,
            "editable": true,
            "label": "Configured Package",
            "path": "properties.package_image_id"
        },
        "parameters": {
            "properties": {
                "domain": {
                    "viewable": true,
                    "editable": true,
                    "label": "Domain",
                    "path": "properties.parameters.properties.domain"
                },
                "subnet_mask": {
                    "viewable": true,
                    "editable": true,
                    "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                    "label": "IP/MASK",
                    "path": "properties.parameters.properties.subnet_mask"
                },
                "gateway": {
                    "viewable": true,
                    "editable": true,
                    "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                    "label": "Gateway",
                    "path": "properties.parameters.properties.gateway"
                },
                "password": {
                    "viewable": true,
                    "editable": true,
                    "label": "Password",
                    "path": "properties.parameters.properties.password"
                },
                "provision": {
                    "properties": {
                        "contrail": {
                            "properties": {
                                "xmpp_auth_enable": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "XMPP Auth",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.xmpp_auth_enable"
                                },
                                "xmpp_dns_auth_enable": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "XMPP DNS Auth",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.xmpp_dns_auth_enable"
                                },
                                "kernel_upgrade": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "Kernel Upgrade",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.kernel_upgrade"
                                },
                                "kernel_version": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "Kernel Version",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.kernel_version"
                                },
                                "enable_lbass": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "Enable",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.enable_lbass"
                                },
                                "ha": {
                                    "properties": {
                                        "haproxy_enable": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "HA Proxy",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.ha.properties.haproxy_enable"
                                        },
                                        "contrail_internal_vip": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "Contrail Internal VIP",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.ha.properties.contrail_internal_vip"
                                        },
                                        "contrail_external_vip": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "Contrail External VIP",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.ha.properties.contrail_external_vip"
                                        },
                                        "contrail_internal_virtual_router_id": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Contrail Internal Virtual Router ID",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.ha.properties.contrail_internal_virtual_router_id"
                                        },
                                        "qqcontrail_internal_virtual_router_id": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.ha.properties.qqcontrail_internal_virtual_router_id"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "High Availability",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.ha"
                                },
                                "database": {
                                    "properties": {
                                        "ip_port": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Database IP Port",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.database.properties.ip_port"
                                        },
                                        "directory": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Database Dir",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.database.properties.directory"
                                        },
                                        "minimum_diskGB": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "number",
                                            "label": "Database Min Disk (GB)",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.database.properties.minimum_diskGB"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Database",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.database"
                                },
                                "analytics": {
                                    "properties": {
                                        "data_ttl": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "number",
                                            "label": "Analytics Data TTL",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.data_ttl"
                                        },
                                        "config_audit_ttl": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Analytics Config Audit TTL",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.config_audit_ttl"
                                        },
                                        "statistics_ttl": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Analytics Stats TTL",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.statistics_ttl"
                                        },
                                        "flow_ttl": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Analytics Flow TTL",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.flow_ttl"
                                        },
                                        "snmp_scan_frequency": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "SNMP Scan Frequency (Seconds)",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.snmp_scan_frequency"
                                        },
                                        "snmp_fast_scan_frequency": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "SNMP Fast Scan Frequency (Seconds)",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.snmp_fast_scan_frequency"
                                        },
                                        "topology_scan_frequency": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Topology Scan Frequency (Seconds)",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.topology_scan_frequency"
                                        },
                                        "syslog_port": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Analytics Syslog Port",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.syslog_port"
                                        },
                                        "data_directory": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Analytics Data Dir",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.data_directory"
                                        },
                                        "ssd_data_directory": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "SSD Data Dir",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.ssd_data_directory"
                                        },
                                        "redis_password": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics.properties.redis_password"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Analytics",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.analytics"
                                },
                                "control": {
                                    "properties": {
                                        "encapsulation_priority": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Encapsulation Priority",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.control.properties.encapsulation_priority"
                                        },
                                        "router_asn": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Router ASN",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.control.properties.router_asn"
                                        },
                                        "external_bgp": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "External BGP",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.control.properties.external_bgp"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Control",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.control"
                                },
                                "config": {
                                    "properties": {
                                        "manage_neutron": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.config.properties.manage_neutron"
                                        },
                                        "zookeeper_ip_port": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Zookeeper IP Port",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.config.properties.zookeeper_ip_port"
                                        },
                                        "healthcheck_interval": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Health Check Interval",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.config.properties.healthcheck_interval"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Config",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.config"
                                },
                                "webui": {
                                    "properties": {},
                                    "viewable": true,
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.webui"
                                },
                                "compute": {
                                    "properties": {
                                        "huge_pages": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.compute.properties.huge_pages"
                                        },
                                        "core_mask": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.compute.properties.core_mask"
                                        },
                                        "sriov": {
                                            "properties": {
                                                "enable": {
                                                    "viewable": true,
                                                    "editable": true,
                                                    "label": "Enable SRIOV",
                                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.compute.properties.sriov.properties.enable"
                                                }
                                            },
                                            "viewable": true,
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.compute.properties.sriov"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Compute",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.compute"
                                },
                                "vmware": {
                                    "properties": {
                                        "ip": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "VMware IP",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vmware.properties.ip"
                                        },
                                        "username": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "VMware Username",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vmware.properties.username"
                                        },
                                        "password": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "VMware Password",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vmware.properties.password"
                                        },
                                        "vswitch": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "VMware vSwitch",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vmware.properties.vswitch"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "VMware",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.vmware"
                                },
                                "vgw": {
                                    "properties": {
                                        "public_subnet": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Virtual Gateway Public Subnet",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vgw.properties.public_subnet"
                                        },
                                        "public_vn_name": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Virtual Gateway Public VN Name",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vgw.properties.public_vn_name"
                                        },
                                        "interface": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Virtual Gateway Interface",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vgw.properties.interface"
                                        },
                                        "gateway_routes": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Virtual Gateway Routes",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.vgw.properties.gateway_routes"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.vgw"
                                },
                                "storage": {
                                    "properties": {
                                        "storage_monitor_secret": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Monitoring Key",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_monitor_secret"
                                        },
                                        "osd_bootstrap_key": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "OSD Bootstrap Key",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.osd_bootstrap_key"
                                        },
                                        "storage_chassis_config": {
                                            "items": {
                                                "type": "string"
                                            },
                                            "viewable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_chassis_config"
                                        },
                                        "live_migration_host": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Live Migration NFS Host",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.live_migration_host"
                                        },
                                        "live_migration_ip": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Live Migration IP",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.live_migration_ip"
                                        },
                                        "live_migration_storage_scope": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Live Migration Storage Scope",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.live_migration_storage_scope"
                                        },
                                        "storage_num_osd": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage Num OSD",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_num_osd"
                                        },
                                        "storage_fsid": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage FSID",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_fsid"
                                        },
                                        "storage_num_hosts": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage Num Hosts",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_num_hosts"
                                        },
                                        "storage_admin_key": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage Admin Key",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_admin_key"
                                        },
                                        "storage_virsh_uuid": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage Virsh UUID",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_virsh_uuid"
                                        },
                                        "storage_cluster_network": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Storage Cluster Network",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_cluster_network"
                                        },
                                        "storage_enabled": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.contrail.properties.storage.properties.storage_enabled"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "Storage",
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.storage"
                                },
                                "toragent": {
                                    "properties": {},
                                    "viewable": true,
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.toragent"
                                },
                                "tsn": {
                                    "properties": {},
                                    "viewable": true,
                                    "path": "properties.parameters.properties.provision.properties.contrail.properties.tsn"
                                }
                            },
                            "viewable": true,
                            "label": "Contrail",
                            "path": "properties.parameters.properties.provision.properties.contrail"
                        },
                        "openstack": {
                            "properties": {
                                "keystone": {
                                    "properties": {
                                        "admin_password": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Keystone Admin Password",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.admin_password"
                                        },
                                        "ip": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "Keystone IP",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.ip"
                                        },
                                        "admin_user": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Keystone Admin Username",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.admin_user"
                                        },
                                        "admin_tenant": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Keystone Admin Tenant",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.admin_tenant"
                                        },
                                        "service_tenant": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Keystone Service Tenant",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.service_tenant"
                                        },
                                        "auth_port": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.auth_port"
                                        },
                                        "auth_protocol": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone.properties.auth_protocol"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.keystone"
                                },
                                "neutron": {
                                    "properties": {
                                        "service_protocol": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Neutron Service Protocol",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.neutron.properties.service_protocol"
                                        },
                                        "port": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Neutron Port",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.neutron.properties.port"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.neutron"
                                },
                                "amqp": {
                                    "properties": {
                                        "server_ip": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "AMQP Server IP",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.amqp.properties.server_ip"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.amqp"
                                },
                                "region": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.region"
                                },
                                "multi_tenancy": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "Multi Tenancy",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.multi_tenancy"
                                },
                                "openstack_manage_amqp": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "Openstack Managed AMQP",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.openstack_manage_amqp"
                                },
                                "enable_ceilometer": {
                                    "viewable": true,
                                    "editable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.enable_ceilometer"
                                },
                                "ha": {
                                    "properties": {
                                        "internal_vip": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "Internal VIP",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.internal_vip"
                                        },
                                        "external_vip": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "External VIP",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.external_vip"
                                        },
                                        "internal_virtual_router_id": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "Internal Virtual Router ID",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.internal_virtual_router_id"
                                        },
                                        "external_virtual_router_id": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "External Virtual Router ID",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.external_virtual_router_id"
                                        },
                                        "nfs_server": {
                                            "viewable": true,
                                            "editable": true,
                                            "pattern": "^$|^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(/[0-9][0-9])?$",
                                            "label": "NFS Server",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.nfs_server"
                                        },
                                        "nfs_glance_path": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "NFS Glance Path",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.ha.properties.nfs_glance_path"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "High Availability",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.ha"
                                },
                                "mysql": {
                                    "properties": {
                                        "root_password": {
                                            "viewable": true,
                                            "editable": true,
                                            "label": "MySQL Root Password",
                                            "path": "properties.parameters.properties.provision.properties.openstack.properties.mysql.properties.root_password"
                                        }
                                    },
                                    "viewable": true,
                                    "label": "",
                                    "path": "properties.parameters.properties.provision.properties.openstack.properties.mysql"
                                }
                            },
                            "viewable": true,
                            "label": "Openstack",
                            "path": "properties.parameters.properties.provision.properties.openstack"
                        }
                    },
                    "viewable": true,
                    "label": "Provision",
                    "path": "properties.parameters.properties.provision"
                }
            },
            "viewable": true,
            "label": "Parameters",
            "path": "properties.parameters"
        }
    },
    "viewable": true,
    "path": ""
};});
