/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

// File generated by Makefile target ui-schemas
define([], function(){ return {
    "properties": {
        "id": {
            "viewable": true,
            "editable": false,
            "label": "ID",
            "path": "properties.id"
        },
        "category": {
            "viewable": true,
            "editable": true,
            "label": "Category",
            "path": "properties.category"
        },
        "type": {
            "viewable": true,
            "editable": true,
            "label": "Type",
            "path": "properties.type"
        },
        "version": {
            "viewable": true,
            "editable": true,
            "label": "Version",
            "path": "properties.version"
        },
        "path": {
            "viewable": true,
            "editable": true,
            "label": "Path",
            "path": "properties.path"
        },
        "parameters": {
            "properties": {},
            "viewable": true,
            "label": "Parameters",
            "path": "properties.parameters"
        }
    },
    "viewable": true,
    "path": ""
};});
