/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

// File generated by Makefile target ui-schemas
define([], function(){ return {
    "properties": {
        "id": {
            "viewable": true,
            "editable": false,
            "label": "ID",
            "path": "properties.id"
        },
        "category": {
            "viewable": true,
            "editable": true,
            "label": "Category",
            "path": "properties.category"
        },
        "type": {
            "viewable": true,
            "editable": true,
            "label": "Type",
            "path": "properties.type"
        },
        "version": {
            "viewable": true,
            "editable": true,
            "label": "Version",
            "path": "properties.version"
        },
        "path": {
            "viewable": true,
            "editable": true,
            "label": "Path",
            "path": "properties.path"
        },
        "parameters": {
            "properties": {
                "puppet_manifest_version": {
                    "viewable": true,
                    "editable": true,
                    "label": "",
                    "path": "properties.parameters.properties.puppet_manifest_version"
                },
                "kickstart": {
                    "viewable": true,
                    "editable": true,
                    "label": "Kickstart",
                    "path": "properties.parameters.properties.kickstart"
                },
                "version": {
                    "viewable": true,
                    "editable": true,
                    "label": "Version",
                    "path": "properties.parameters.properties.version"
                },
                "kickseed": {
                    "viewable": true,
                    "editable": true,
                    "label": "Kickseed",
                    "path": "properties.parameters.properties.kickseed"
                },
                "sequence_provisioning_available": {
                    "viewable": true,
                    "editable": true,
                    "label": "",
                    "path": "properties.parameters.properties.sequence_provisioning_available"
                }
            },
            "viewable": true,
            "path": "properties.parameters"
        },
        "cgrid": {
            "viewable": true,
            "editable": true,
            "type": "string",
            "path": "properties.cgrid"
        }
    },
    "viewable": true,
    "path": ""
}});