var pkgList = {};
exports.pkgList = pkgList;
pkgList['pkgName'] = 'serverManager';
pkgList['parseURL.xml'] = [];
pkgList['jobProcess.xml'] = [];
pkgList['featureList.xml'] = [];
pkgList['roleList.xml'] = [];
pkgList['parseURL.xml'].push('/webroot/common/api/url.routes.js');
pkgList['featureList.xml'].push('/webroot/common/xml/feature.list.js');
pkgList['parseURL.xml'].push('/webroot/config/physicaldevices/baremetal/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/setting/sm/api/url.routes.js');
